//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tugas_besar
{
    using System;
    using System.Collections.Generic;
    
    public partial class pelayanan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pelayanan()
        {
            this.transaksis = new HashSet<transaksi>();
        }
    
        public int Id { get; set; }
        public string jenis_pelayanan { get; set; }
        public string nama_pelayanan { get; set; }
        public int id_dokter { get; set; }
    
        public virtual dokter dokter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transaksi> transaksis { get; set; }
    }
}
