//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tugas_besar
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseSIDokterHewanEntities1 : DbContext
    {
        public DatabaseSIDokterHewanEntities1()
            : base("name=DatabaseSIDokterHewanEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<daftar> daftars { get; set; }
        public virtual DbSet<dokter> dokters { get; set; }
        public virtual DbSet<pelayanan> pelayanans { get; set; }
        public virtual DbSet<transaksi> transaksis { get; set; }
    }
}
