//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tugas_besar
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaksi
    {
        public int Id { get; set; }
        public int id_user { get; set; }
        public string jenis_hewan { get; set; }
        public string umur { get; set; }
        public int id_pelayanan { get; set; }
        public System.DateTime tanggal { get; set; }
    
        public virtual daftar daftar { get; set; }
        public virtual pelayanan pelayanan { get; set; }
    }
}
